# Activate the environmet to run the code using "source activate bttb"
# or "activate bttb" on Windows.
name: bttb
channels:
    - defaults
    - conda-forge
dependencies:
    - python=2.7
    - pip
    - future
    - numpy
    - scipy
    - matplotlib
    - jupyter
    - pytest
    - pytest-cov
    - flake8
    - fatiando=0.5
